# azure-pipelines.yml
trigger: none
pr:
  branches:
    include:
      - main

variables:
  DOTNET_VERSION: '8.0.x'
  DRY_RUN: 'false'

stages:
  - stage: AI_PR_Review
    displayName: "AI PR Review"
    jobs:
      - job: RunAiReview
        displayName: "Run AI PR Reviewer"
        pool:
          vmImage: 'windows-latest'
        steps:
          - checkout: self
            persistCredentials: true

          - task: UseDotNet@2
            displayName: "Install .NET $(DOTNET_VERSION)"
            inputs:
              packageType: 'sdk'
              version: '$(DOTNET_VERSION)'

          - pwsh: |
              Write-Host "Setting up .env from secure files/variables"
              New-Item -ItemType Directory -Force -Path "$(Build.SourcesDirectory)\secrets" | Out-Null
              Set-Content -Path "$(Build.SourcesDirectory)\secrets\.env" -Value "$(ENV_FILE_CONTENT)" -NoNewline
            displayName: "Materialize .env file"
            env:
              ENV_FILE_CONTENT: '$(ENV_FILE_CONTENT)'

          - pwsh: |
              if (-not $env:Quaaly_REPO_URL) {
                Write-Error "Quaaly_REPO_URL environment variable is not set"
                exit 1
              }
              Write-Host "Cloning Quaaly repository from: $env:Quaaly_REPO_URL"
              New-Item -ItemType Directory -Force -Path "$(Build.SourcesDirectory)\Quaaly-clone" | Out-Null
              git clone $env:Quaaly_REPO_URL "$(Build.SourcesDirectory)\Quaaly-clone"
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Failed to clone Quaaly repository"
                exit 1
              }
              Write-Host "Successfully cloned Quaaly repository"
            displayName: "Clone Quaaly Repository"
            env:
              Quaaly_REPO_URL: '$(Quaaly_REPO_URL)'

          - pwsh: |
              Write-Host "Restoring Quaaly project..."
              dotnet restore "$(Build.SourcesDirectory)\Quaaly-clone\Quaaly\Quaaly.csproj"
              if ($LASTEXITCODE -ne 0) {
                Write-Error "dotnet restore failed"
                exit 1
              }
            displayName: "Restore Quaaly"
            condition: ne(variables['DRY_RUN'], 'skip')

          - pwsh: |
              Write-Host "Building Quaaly project..."
              dotnet build "$(Build.SourcesDirectory)\Quaaly-clone\Quaaly\Quaaly.csproj" --configuration Release --no-restore
              if ($LASTEXITCODE -ne 0) {
                Write-Error "dotnet build failed"
                exit 1
              }
            displayName: "Build Quaaly"
            condition: ne(variables['DRY_RUN'], 'skip')

          - pwsh: |
              Write-Host "Running Quaaly..."
              $envFilePath = "$(Build.SourcesDirectory)\secrets\.env"
              if (Test-Path $envFilePath) {
                Write-Host "Loading environment variables from .env file"
                Get-Content $envFilePath | ForEach-Object {
                  if ($_ -match '^([^#][^=]+)=(.*)$') {
                    [Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                  }
                }
              }
              
              $env:ADO_ACCESS_TOKEN = "$(System.AccessToken)"
              $env:DRY_RUN = "$(DRY_RUN)"
              $env:REVIEW_SCOPE = "$(REVIEW_SCOPE)"
              $env:ADO_COLLECTION_URL = "$(System.CollectionUri)"
              $env:ADO_PROJECT = "$(System.TeamProject)"
              $env:ADO_REPO_ID = "$(Build.Repository.ID)"
              $env:ADO_PR_ID = "$(System.PullRequest.PullRequestId)"
              $env:BUILD_SOURCEVERSION = "$(Build.SourceVersion)"
              $env:LOCAL_REPO_PATH = "$(Build.SourcesDirectory)"
              
              Set-Location "$(Build.SourcesDirectory)"
              dotnet run --configuration Release --project "$(Build.SourcesDirectory)\Quaaly-clone\Quaaly\Quaaly.csproj" --no-build
              if ($LASTEXITCODE -ne 0) {
                Write-Error "Quaaly execution failed"
                exit 1
              }
            displayName: "Run AI PR Reviewer"
            env:
              REVIEW_SCOPE: '$(REVIEW_SCOPE)'
            condition: ne(variables['DRY_RUN'], 'skip')

        variables:
          REVIEW_SCOPE: 'changed-files'
        workspace:
          clean: all
        timeoutInMinutes: 120
        continueOnError: false
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: '1'
